import React, { useMemo, useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Images } from '@/constants/assets'; import { useAuth } from '@/services/AuthProvider'; import { useHousehold } from '@/services/HouseholdContext'; import { colors, font, s } from '@/theme'; import { avatarImages, avatarNames, Card, Header } from './HouseholdUI'; import type { SetupStack } from './HouseholdSetupNavigator';

export function CreateHouseholdView({ navigation }: NativeStackScreenProps<SetupStack, 'Create'>) {
  const { user } = useAuth(); const household = useHousehold(); const [householdName, setHouseholdName] = useState(''); const [yourName, setYourName] = useState(user?.displayName ?? ''); const [avatar, setAvatar] = useState('member1'); const [members, setMembers] = useState(['']);
  const duplicateKeys = useMemo(() => { const values = [yourName, ...members].map(value => value.trim().toLowerCase()).filter(Boolean); return new Set(values.filter((value, index) => values.indexOf(value) !== index)); }, [yourName, members]);
  const canCreate = Boolean(householdName.trim() && yourName.trim() && duplicateKeys.size === 0);
  const updateMember = (index: number, value: string) => setMembers(current => current.map((item, i) => i === index ? value.slice(0, 20) : item));
  return <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Header title="Create Household" onBack={() => navigation.goBack()} /></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Card><Label>Household Name*</Label><Field placeholder="e.g. The Smith Home" value={householdName} onChangeText={value => setHouseholdName(value.slice(0, 30))} /></Card><Card><Label>Your Name*</Label><Field placeholder="Enter your name" value={yourName} onChangeText={value => setYourName(value.slice(0, 20))} />{duplicateKeys.has(yourName.trim().toLowerCase()) && <ErrorText />}<Label>Choose Your Avatar</Label><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.avatars}>{avatarImages.map((source, index) => <Pressable key={avatarNames[index]} onPress={() => setAvatar(avatarNames[index])}><Image source={source} style={[styles.avatar, avatar === avatarNames[index] && styles.avatarSelected]} /></Pressable>)}</ScrollView></Card><Card><View style={styles.labelRow}><Label>Family Members</Label><Text style={styles.optional}>Optional</Text></View><Text style={styles.help}>Add a slot for each family member. They pick their name when they join with your code.</Text>{members.map((value, index) => <View key={index}><View style={styles.memberRow}><Field placeholder="Member name" value={value} onChangeText={next => updateMember(index, next)} grow /><Pressable style={styles.minus} onPress={() => setMembers(current => current.filter((_, i) => i !== index))}><Text style={styles.minusText}>−</Text></Pressable></View>{duplicateKeys.has(value.trim().toLowerCase()) && <ErrorText />}</View>)}<Pressable disabled={members.some(value => !value.trim())} onPress={() => setMembers(current => [...current, ''])} style={styles.add}><Image source={Images.plusIcon} style={styles.plus} /><Text style={styles.addText}>Add Member</Text></Pressable></Card></ScrollView><View style={styles.footer}><Pressable disabled={!canCreate || household.isWorking} onPress={() => { void household.createHousehold(householdName.trim(), yourName.trim(), avatar, members.map(value => value.trim()).filter(Boolean)); }} style={[styles.create, (!canCreate || household.isWorking) && styles.disabled]}>{household.isWorking ? <ActivityIndicator color="white" /> : <Text style={styles.createText}>Create Household</Text>}</Pressable>{household.error && <Text style={styles.error}>{household.error}</Text>}</View></KeyboardAvoidingView>;
}
function Label({ children }: React.PropsWithChildren) { return <Text style={styles.label}>{children}</Text>; } function ErrorText() { return <Text style={styles.error}>This name is already used. Please pick a different one.</Text>; } function Field(props: React.ComponentProps<typeof TextInput> & { grow?: boolean }) { return <TextInput {...props} placeholderTextColor={`${colors.text}66`} style={[styles.field, props.grow && { flex: 1 }]} />; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, header: { paddingTop: s(55), paddingHorizontal: s(15) }, content: { padding: s(15), gap: s(15), paddingBottom: s(150) }, label: { ...font('medium', 14), color: `${colors.text}CC`, marginBottom: s(10) }, field: { height: s(48), borderRadius: s(16), backgroundColor: colors.background, borderWidth: 1, borderColor: `${colors.text}1A`, paddingHorizontal: s(14), ...font('regular', 14), color: colors.text, marginBottom: s(15) }, avatars: { gap: s(10), padding: s(2) }, avatar: { width: s(48), height: s(48), borderRadius: s(24) }, avatarSelected: { borderWidth: 2, borderColor: colors.purple }, labelRow: { flexDirection: 'row', justifyContent: 'space-between' }, optional: { ...font('regular', 12), color: `${colors.text}66` }, help: { ...font('regular', 12), color: `${colors.text}80`, marginBottom: s(12) }, memberRow: { flexDirection: 'row', gap: s(10), alignItems: 'center' }, minus: { width: s(36), height: s(36), borderRadius: s(18), backgroundColor: `${colors.text}0F`, alignItems: 'center', justifyContent: 'center', marginBottom: s(15) }, minusText: { ...font('semibold', 20), color: `${colors.text}80` }, add: { height: s(44), borderRadius: s(12), borderWidth: 1, borderStyle: 'dashed', borderColor: `${colors.purple}66`, flexDirection: 'row', gap: s(8), alignItems: 'center', justifyContent: 'center' }, plus: { width: s(20), height: s(20), tintColor: colors.purple }, addText: { ...font('medium', 14), color: colors.purple }, footer: { position: 'absolute', left: s(25), right: s(25), bottom: s(20) }, create: { height: s(52), borderRadius: s(26), backgroundColor: colors.purple, alignItems: 'center', justifyContent: 'center' }, createText: { ...font('semibold', 16), color: 'white' }, disabled: { opacity: 0.5 }, error: { ...font('regular', 12), color: '#FF6262', marginBottom: s(8), textAlign: 'center' } });
