import React, { useEffect, useRef } from 'react';
import { Animated, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Images } from '@/constants/assets'; import { colors, font, s } from '@/theme'; import type { SetupStack } from './HouseholdSetupNavigator';
import { useScreenTracking } from '@/services/Analytics';
import { AnimatedAppImage } from '@/components/AppImage';
import { SoftGlow } from '@/components/motion';
export function HouseholdSetupView({ navigation }: NativeStackScreenProps<SetupStack, 'Choice'>) { useScreenTracking('HouseholdSetup'); const insets = useSafeAreaInsets(); const float = useRef(new Animated.Value(0)).current; useEffect(() => { Animated.loop(Animated.sequence([Animated.timing(float, { toValue: s(-8), duration: 1600, useNativeDriver: true }), Animated.timing(float, { toValue: 0, duration: 1600, useNativeDriver: true })])).start(); }, [float]); return <View style={styles.root}><View style={styles.spacer} /><View style={styles.art}><SoftGlow color={colors.purple} opacity={0.18} style={styles.glow} /><AnimatedAppImage source={Images.memberEmpty} resizeMode="contain" style={[styles.image, { transform: [{ translateY: float }] }]} /></View><Text style={styles.title}>Set Up Your Home</Text><Text style={styles.body}>Create a new household or join an existing one to start sharing chores with your family.</Text><View style={styles.flex} /><View style={[styles.actions, { paddingBottom: Math.max(s(30), insets.bottom + s(16)) }]}><Pressable onPress={() => navigation.push('Create')} style={styles.primary}><Text style={styles.primaryText}>Create New Household</Text></Pressable><Pressable onPress={() => navigation.push('Join')} style={styles.secondary}><Text style={styles.secondaryText}>Join Existing</Text></Pressable></View></View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background, alignItems: 'center' }, spacer: { flex: 0.7 }, art: { width: s(180), height: s(180), alignItems: 'center', justifyContent: 'center' }, glow: { position: 'absolute' }, image: { width: s(170), height: s(170) }, title: { ...font('semibold', 24), color: colors.text, marginTop: s(28) }, body: { ...font('regular', 15), color: `${colors.text}99`, textAlign: 'center', width: s(280), marginTop: s(12) }, flex: { flex: 1 }, actions: { width: '100%', paddingHorizontal: s(25), paddingBottom: s(30), gap: s(12) }, primary: { height: s(54), borderRadius: s(27), backgroundColor: colors.purple, alignItems: 'center', justifyContent: 'center' }, primaryText: { ...font('semibold', 16), color: 'white' }, secondary: { height: s(54), borderRadius: s(27), backgroundColor: `${colors.purple}1A`, borderWidth: 1, borderColor: `${colors.purple}4D`, alignItems: 'center', justifyContent: 'center' }, secondaryText: { ...font('semibold', 16), color: colors.purple } });
