import React, { useRef, useState } from 'react';
import { ActivityIndicator, Animated, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import type { NativeStackScreenProps } from '@react-navigation/native-stack'; import { Images } from '@/constants/assets'; import { useHousehold } from '@/services/HouseholdContext'; import { colors, font, s } from '@/theme'; import { Header } from './HouseholdUI'; import type { SetupStack } from './HouseholdSetupNavigator';
import { useScreenTracking } from '@/services/Analytics';
import { AppImage } from '@/components/AppImage';
import { SoftGlow } from '@/components/motion';
export function JoinHouseholdView({ navigation }: NativeStackScreenProps<SetupStack, 'Join'>) { useScreenTracking('JoinHousehold'); const insets = useSafeAreaInsets(); const manager = useHousehold(); const [code, setCode] = useState(''); const scale = useRef(new Animated.Value(1)).current; const lookup = async () => { const result = await manager.lookupHousehold(code); if (result) navigation.push('MemberSelect', result); }; return <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Header title="Join Household" onBack={() => navigation.goBack()} /></View><View style={styles.center}><View style={styles.art}><SoftGlow color={colors.purple} opacity={0.12} style={styles.glow} /><AppImage source={Images.memberEmpty} resizeMode="contain" style={styles.image} /></View><Text style={styles.title}>Enter Invite Code</Text><Text style={styles.body}>Ask a family member for the household invite code.</Text><TextInput autoCapitalize="characters" autoCorrect={false} value={code} onChangeText={value => setCode(value.toUpperCase().slice(0, 6))} placeholder="ABC123" placeholderTextColor={`${colors.text}40`} style={styles.code} /></View><View style={[styles.footer, { paddingBottom: Math.max(s(20), insets.bottom + s(12)) }]}><Animated.View style={{ transform: [{ scale }] }}><Pressable disabled={code.trim().length !== 6 || manager.isWorking} onPressIn={() => Animated.spring(scale, { toValue: 0.92, useNativeDriver: true }).start()} onPressOut={() => Animated.spring(scale, { toValue: 1, useNativeDriver: true }).start()} onPress={() => { void lookup(); }} style={[styles.continue, (code.trim().length !== 6 || manager.isWorking) && styles.disabled]}>{manager.isWorking ? <ActivityIndicator color="white" /> : <Text style={styles.continueText}>Continue</Text>}</Pressable></Animated.View>{manager.error && <Text style={styles.error}>{manager.error}</Text>}</View></KeyboardAvoidingView>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, header: { paddingTop: s(55), paddingHorizontal: s(15) }, center: { flex: 1, alignItems: 'center', paddingTop: s(40) }, art: { width: s(160), height: s(160), alignItems: 'center', justifyContent: 'center' }, glow: { position: 'absolute' }, image: { width: s(150), height: s(150) }, title: { ...font('semibold', 18), color: colors.text, marginTop: s(28) }, body: { ...font('regular', 15), color: `${colors.text}99`, width: s(250), textAlign: 'center', marginTop: s(10) }, code: { width: s(325), height: s(56), borderRadius: s(16), backgroundColor: 'white', borderWidth: s(1.5), borderColor: `${colors.purple}4D`, textAlign: 'center', ...font('bold', 22), color: colors.text, marginTop: s(28), letterSpacing: s(3) }, footer: { paddingHorizontal: s(25), paddingBottom: s(20) }, continue: { height: s(52), borderRadius: s(26), backgroundColor: colors.purple, alignItems: 'center', justifyContent: 'center' }, continueText: { ...font('semibold', 16), color: 'white' }, disabled: { opacity: 0.5 }, error: { ...font('regular', 12), color: '#FF6262', textAlign: 'center', marginTop: s(8) } });
