import React, { useEffect, useRef, useState } from 'react';
import { Animated, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Images } from '@/constants/assets';
import { AppButton } from '@/components/AppButton';
import { colors, font, s } from '@/theme';

export function GiftPaywallView({ onClose }: { onClose(): void }) {
  const [seconds, setSeconds] = useState(23 * 3600 + 15 * 60 + 23);
  const nudge = useRef(new Animated.Value(0)).current;
  useEffect(() => { const timer = setInterval(() => setSeconds(v => Math.max(0, v - 1)), 1000); Animated.loop(Animated.sequence([Animated.timing(nudge, { toValue: s(5), duration: 600, useNativeDriver: true }), Animated.timing(nudge, { toValue: 0, duration: 600, useNativeDriver: true })])).start(); return () => clearInterval(timer); }, [nudge]);
  const values = [Math.floor(seconds / 3600), Math.floor(seconds / 60) % 60, seconds % 60];
  return <View style={styles.root}><LinearGradient colors={[`${colors.purple}33`, colors.background]} style={styles.top} /><Pressable onPress={onClose} style={styles.skip}><Text style={styles.skipText}>Skip</Text></Pressable><Image source={Images.giftImg} resizeMode="contain" style={styles.gift} /><Text style={styles.off}>67% OFF</Text><Text style={styles.yearly}>On Yearly Plan</Text><View style={styles.card}><Text style={styles.expires}>Expires in</Text><View style={styles.timer}>{values.map((value, i) => <React.Fragment key={i}><View><View style={styles.timeBox}><Text style={styles.time}>{String(value).padStart(2, '0')}</Text></View><Text style={styles.timeLabel}>{['Hours', 'Minutes', 'Seconds'][i]}</Text></View>{i < 2 && <Text style={styles.colon}>:</Text>}</React.Fragment>)}</View></View><View style={styles.price}><Text style={styles.old}>$29.99{`\n`}<Text style={styles.period}>Yearly</Text></Text><Animated.Image source={Images.giftArrow} resizeMode="contain" style={[styles.arrow, { transform: [{ translateX: nudge }] }]} /><Text style={styles.new}>$9.99{`\n`}<Text style={styles.period}>Yearly</Text></Text></View><View style={styles.cta}><AppButton title="Collect Gift" onPress={onClose} /></View></View>;
}

const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background, alignItems: 'center' }, top: { ...StyleSheet.absoluteFillObject, bottom: undefined, height: s(301) }, skip: { position: 'absolute', right: s(20), top: s(55), zIndex: 2, padding: s(8) }, skipText: { ...font('medium', 15), color: colors.text }, gift: { width: s(272), height: s(275), marginTop: s(42) }, off: { ...font('bold', 60), color: colors.purple, marginTop: s(-38) }, yearly: { ...font('semibold', 26), color: colors.text }, card: { width: s(325), height: s(147), borderRadius: s(24), borderWidth: 1, borderColor: `${colors.purple}55`, marginTop: s(16), alignItems: 'center', justifyContent: 'center' }, expires: { ...font('medium', 15), color: colors.text, marginBottom: s(10) }, timer: { flexDirection: 'row', alignItems: 'center', gap: s(7) }, timeBox: { width: s(68), height: s(50), borderRadius: s(12), backgroundColor: colors.purple, alignItems: 'center', justifyContent: 'center' }, time: { ...font('bold', 18), color: 'white' }, timeLabel: { ...font('regular', 10), color: `${colors.text}99`, textAlign: 'center', marginTop: s(4) }, colon: { ...font('bold', 20), color: colors.purple, marginTop: s(-16) }, price: { flexDirection: 'row', alignItems: 'center', marginTop: s(18), gap: s(16) }, old: { ...font('semibold', 20), color: `${colors.text}80`, textDecorationLine: 'line-through', textAlign: 'center' }, new: { ...font('bold', 20), color: colors.purple, textAlign: 'center' }, period: { ...font('regular', 12), textDecorationLine: 'none' }, arrow: { width: s(65), height: s(28) }, cta: { position: 'absolute', left: s(25), right: s(25), bottom: s(38) } });
