// Generated from the iOS ChoreBuddy asset catalog. Do not hand-edit.
import choreArrowIconSvg from '../../assets/catalog/choreArrowIcon.svg';
import choreCalendarIconSvg from '../../assets/catalog/choreCalendarIcon.svg';
import choreChevronIconSvg from '../../assets/catalog/choreChevronIcon.svg';
import choreSearchIconSvg from '../../assets/catalog/choreSearchIcon.svg';
import choreTrashIconSvg from '../../assets/catalog/choreTrashIcon.svg';
import morePhotosSvg from '../../assets/catalog/morePhotos.svg';
import moreReminderSvg from '../../assets/catalog/moreReminder.svg';
import moreSubtasksSvg from '../../assets/catalog/moreSubtasks.svg';
import schedAlarmSvg from '../../assets/catalog/schedAlarm.svg';
import schedCustomSvg from '../../assets/catalog/schedCustom.svg';
import schedDailySvg from '../../assets/catalog/schedDaily.svg';
import schedOneTimeSvg from '../../assets/catalog/schedOneTime.svg';
import zoneBathtubSvg from '../../assets/catalog/zoneBathtub.svg';
import zoneBedSvg from '../../assets/catalog/zoneBed.svg';
import zoneCookingSvg from '../../assets/catalog/zoneCooking.svg';
import zoneCouchSvg from '../../assets/catalog/zoneCouch.svg';
import chartDownloadIconSvg from '../../assets/catalog/chartDownloadIcon.svg';
import chartPrintIconSvg from '../../assets/catalog/chartPrintIcon.svg';
import dueOnIconSvg from '../../assets/catalog/dueOnIcon.svg';
import statusDoneIconSvg from '../../assets/catalog/statusDoneIcon.svg';
import statusResetIconSvg from '../../assets/catalog/statusResetIcon.svg';
import statusSkipIconSvg from '../../assets/catalog/statusSkipIcon.svg';
import statusSnoozeIconSvg from '../../assets/catalog/statusSnoozeIcon.svg';
import skipIconSvg from '../../assets/catalog/skipIcon.svg';
import undoIconSvg from '../../assets/catalog/undoIcon.svg';
import copyIconSvg from '../../assets/catalog/copyIcon.svg';
import editIconSvg from '../../assets/catalog/editIcon.svg';
import memberAddIconSvg from '../../assets/catalog/memberAddIcon.svg';
import shareIconSvg from '../../assets/catalog/shareIcon.svg';
import trashIconSvg from '../../assets/catalog/trashIcon.svg';
import calendarGlyphIconSvg from '../../assets/catalog/calendarGlyphIcon.svg';
import statusCheckIconSvg from '../../assets/catalog/statusCheckIcon.svg';
import statusMinusIconSvg from '../../assets/catalog/statusMinusIcon.svg';
import statusXIconSvg from '../../assets/catalog/statusXIcon.svg';
import shieldIconSvg from '../../assets/catalog/shieldIcon.svg';
import deleteIconSvg from '../../assets/catalog/deleteIcon.svg';
import logoutIconSvg from '../../assets/catalog/logoutIcon.svg';
import zoneCalendarIconSvg from '../../assets/catalog/zoneCalendarIcon.svg';
import zoneDownloadIconSvg from '../../assets/catalog/zoneDownloadIcon.svg';
import editZoneIconSvg from '../../assets/catalog/editZoneIcon.svg';
import markDoneIconSvg from '../../assets/catalog/markDoneIcon.svg';
import moreVerticalIconSvg from '../../assets/catalog/moreVerticalIcon.svg';

export const Images = {
  addPresetIcon: require('../../assets/catalog/addPresetIcon.png'),
  bunnyPeek: require('../../assets/catalog/bunnyPeek.png'),
  bunnyPeek2: require('../../assets/catalog/bunnyPeek2.png'),
  choreArrowIcon: choreArrowIconSvg,
  choreCalendarIcon: choreCalendarIconSvg,
  choreCheckbox: require('../../assets/catalog/choreCheckbox.png'),
  choreChevronIcon: choreChevronIconSvg,
  choreSearchIcon: choreSearchIconSvg,
  choreTrashIcon: choreTrashIconSvg,
  circleBg1: require('../../assets/catalog/circleBg1.png'),
  circleBg2: require('../../assets/catalog/circleBg2.png'),
  customChoreIcon: require('../../assets/catalog/customChoreIcon.png'),
  morePhotos: morePhotosSvg,
  moreReminder: moreReminderSvg,
  moreSubtasks: moreSubtasksSvg,
  schedAlarm: schedAlarmSvg,
  schedCustom: schedCustomSvg,
  schedDaily: schedDailySvg,
  schedOneTime: schedOneTimeSvg,
  zoneBathtub: zoneBathtubSvg,
  zoneBed: zoneBedSvg,
  zoneCooking: zoneCookingSvg,
  zoneCouch: zoneCouchSvg,
  chartDownloadIcon: chartDownloadIconSvg,
  chartPrintIcon: chartPrintIconSvg,
  dueOnIcon: dueOnIconSvg,
  statusDoneIcon: statusDoneIconSvg,
  statusDoneIcon2: require('../../assets/catalog/statusDoneIcon2.png'),
  statusMascot: require('../../assets/catalog/statusMascot.png'),
  statusResetIcon: statusResetIconSvg,
  statusSkipIcon: statusSkipIconSvg,
  statusSkipIcon2: require('../../assets/catalog/statusSkipIcon2.png'),
  statusSnoozeIcon: statusSnoozeIconSvg,
  statusSnoozeIcon2: require('../../assets/catalog/statusSnoozeIcon2.png'),
  Splash_screen: require('../../assets/catalog/Splash_screen.png'),
  appBg: require('../../assets/catalog/appBg.png'),
  bunnyEyeCloseImg: require('../../assets/catalog/bunnyEyeCloseImg.png'),
  bunnyEyeOpenImg: require('../../assets/catalog/bunnyEyeOpenImg.png'),
  bunnyImg4: require('../../assets/catalog/bunnyImg4.png'),
  bunnyImg5: require('../../assets/catalog/bunnyImg5.png'),
  crownIcon: require('../../assets/catalog/crownIcon.png'),
  emptyImg: require('../../assets/catalog/emptyImg.png'),
  handIcon: require('../../assets/catalog/handIcon.png'),
  ipadGiftBg: require('../../assets/catalog/ipadGiftBg.png'),
  iphoneGiftBg: require('../../assets/catalog/iphoneGiftBg.png'),
  lockIcon: require('../../assets/catalog/lockIcon.png'),
  plusIcon: require('../../assets/catalog/plusIcon.png'),
  proLockIcon: require('../../assets/catalog/proLockIcon.png'),
  rightArrowIcon: require('../../assets/catalog/rightArrowIcon.png'),
  settingsIcon: require('../../assets/catalog/settingsIcon.png'),
  bunnyHeartImg: require('../../assets/catalog/bunnyHeartImg.png'),
  choreBuddyLogo: require('../../assets/catalog/choreBuddyLogo.png'),
  skipIcon: skipIconSvg,
  undoIcon: undoIconSvg,
  appleLogo: require('../../assets/catalog/appleLogo.png'),
  googleLogo: require('../../assets/catalog/googleLogo.png'),
  signInBg: require('../../assets/catalog/signInBg.png'),
  copyIcon: copyIconSvg,
  editIcon: editIconSvg,
  member1: require('../../assets/catalog/member1.png'),
  member10: require('../../assets/catalog/member10.png'),
  member11: require('../../assets/catalog/member11.png'),
  member12: require('../../assets/catalog/member12.png'),
  member13: require('../../assets/catalog/member13.png'),
  member14: require('../../assets/catalog/member14.png'),
  member15: require('../../assets/catalog/member15.png'),
  member16: require('../../assets/catalog/member16.png'),
  member17: require('../../assets/catalog/member17.png'),
  member2: require('../../assets/catalog/member2.png'),
  member3: require('../../assets/catalog/member3.png'),
  member4: require('../../assets/catalog/member4.png'),
  member5: require('../../assets/catalog/member5.png'),
  member6: require('../../assets/catalog/member6.png'),
  member7: require('../../assets/catalog/member7.png'),
  member8: require('../../assets/catalog/member8.png'),
  member9: require('../../assets/catalog/member9.png'),
  memberAddIcon: memberAddIconSvg,
  memberEmpty: require('../../assets/catalog/memberEmpty.png'),
  shareIcon: shareIconSvg,
  trashIcon: trashIconSvg,
  chartIcon: require('../../assets/catalog/chartIcon.png'),
  homeIcon: require('../../assets/catalog/homeIcon.png'),
  scheduleIcon: require('../../assets/catalog/scheduleIcon.png'),
  statsIcon: require('../../assets/catalog/statsIcon.png'),
  zoneIcon: require('../../assets/catalog/zoneIcon.png'),
  bunnyImg1: require('../../assets/catalog/bunnyImg1.png'),
  calendarGlyphIcon: calendarGlyphIconSvg,
  pinkCalendarImg: require('../../assets/catalog/pinkCalendarImg.png'),
  task1Img: require('../../assets/catalog/task1Img.png'),
  task2Img: require('../../assets/catalog/task2Img.png'),
  task3Img: require('../../assets/catalog/task3Img.png'),
  blueColorImg: require('../../assets/catalog/blueColorImg.png'),
  bunnyImg2: require('../../assets/catalog/bunnyImg2.png'),
  checkIcon2: require('../../assets/catalog/checkIcon2.png'),
  checkIcon3: require('../../assets/catalog/checkIcon3.png'),
  darkBlueColorImg: require('../../assets/catalog/darkBlueColorImg.png'),
  darkGreenColorImg: require('../../assets/catalog/darkGreenColorImg.png'),
  greenColorImg: require('../../assets/catalog/greenColorImg.png'),
  purpleColorImg: require('../../assets/catalog/purpleColorImg.png'),
  redColorImg: require('../../assets/catalog/redColorImg.png'),
  yellowColorImg: require('../../assets/catalog/yellowColorImg.png'),
  zone10Icon: require('../../assets/catalog/zone10Icon.png'),
  zone11Icon: require('../../assets/catalog/zone11Icon.png'),
  zone12Icon: require('../../assets/catalog/zone12Icon.png'),
  zone13Icon: require('../../assets/catalog/zone13Icon.png'),
  zone14Icon: require('../../assets/catalog/zone14Icon.png'),
  zone15Icon: require('../../assets/catalog/zone15Icon.png'),
  zone16Icon: require('../../assets/catalog/zone16Icon.png'),
  zone17Icon: require('../../assets/catalog/zone17Icon.png'),
  zone18Icon: require('../../assets/catalog/zone18Icon.png'),
  zone1Icon: require('../../assets/catalog/zone1Icon.png'),
  zone2Icon: require('../../assets/catalog/zone2Icon.png'),
  zone3Icon: require('../../assets/catalog/zone3Icon.png'),
  zone4Icon: require('../../assets/catalog/zone4Icon.png'),
  zone5Icon: require('../../assets/catalog/zone5Icon.png'),
  zone6Icon: require('../../assets/catalog/zone6Icon.png'),
  zone7Icon: require('../../assets/catalog/zone7Icon.png'),
  zone8Icon: require('../../assets/catalog/zone8Icon.png'),
  zone9Icon: require('../../assets/catalog/zone9Icon.png'),
  bunnyFaceImg: require('../../assets/catalog/bunnyFaceImg.png'),
  bunnyLeftHandImg: require('../../assets/catalog/bunnyLeftHandImg.png'),
  bunnyRightHandImg: require('../../assets/catalog/bunnyRightHandImg.png'),
  calendarImg: require('../../assets/catalog/calendarImg.png'),
  floorTaskImg: require('../../assets/catalog/floorTaskImg.png'),
  storageTaskImg: require('../../assets/catalog/storageTaskImg.png'),
  towelsTaskImg: require('../../assets/catalog/towelsTaskImg.png'),
  windowsTaskImg: require('../../assets/catalog/windowsTaskImg.png'),
  avatarIcon1: require('../../assets/catalog/avatarIcon1.png'),
  avatarIcon10: require('../../assets/catalog/avatarIcon10.png'),
  avatarIcon11: require('../../assets/catalog/avatarIcon11.png'),
  avatarIcon12: require('../../assets/catalog/avatarIcon12.png'),
  avatarIcon2: require('../../assets/catalog/avatarIcon2.png'),
  avatarIcon3: require('../../assets/catalog/avatarIcon3.png'),
  avatarIcon4: require('../../assets/catalog/avatarIcon4.png'),
  avatarIcon5: require('../../assets/catalog/avatarIcon5.png'),
  avatarIcon6: require('../../assets/catalog/avatarIcon6.png'),
  avatarIcon7: require('../../assets/catalog/avatarIcon7.png'),
  avatarIcon8: require('../../assets/catalog/avatarIcon8.png'),
  avatarIcon9: require('../../assets/catalog/avatarIcon9.png'),
  crownIcon2: require('../../assets/catalog/crownIcon2.png'),
  bedroomTaskImg: require('../../assets/catalog/bedroomTaskImg.png'),
  bunnyImg3: require('../../assets/catalog/bunnyImg3.png'),
  championIcon: require('../../assets/catalog/championIcon.png'),
  doneImg: require('../../assets/catalog/doneImg.png'),
  kitchenTask2Img: require('../../assets/catalog/kitchenTask2Img.png'),
  kitchenTaskImg: require('../../assets/catalog/kitchenTaskImg.png'),
  missedImg: require('../../assets/catalog/missedImg.png'),
  purpleRectImg: require('../../assets/catalog/purpleRectImg.png'),
  riseArrowIcon: require('../../assets/catalog/riseArrowIcon.png'),
  roomTaskImg: require('../../assets/catalog/roomTaskImg.png'),
  skippedImg: require('../../assets/catalog/skippedImg.png'),
  statusCheckIcon: statusCheckIconSvg,
  statusMinusIcon: statusMinusIconSvg,
  statusXIcon: statusXIconSvg,
  upcomingDayImg: require('../../assets/catalog/upcomingDayImg.png'),
  ipadReminderImg: require('../../assets/catalog/ipadReminderImg.png'),
  iphoneReminerImg: require('../../assets/catalog/iphoneReminerImg.png'),
  onboardingRatingFifthIcon: require('../../assets/catalog/onboardingRatingFifthIcon.png'),
  onboardingRatingFirstIcon: require('../../assets/catalog/onboardingRatingFirstIcon.png'),
  onboardingRatingFourthIcon: require('../../assets/catalog/onboardingRatingFourthIcon.png'),
  onboardingRatingSecondIcon: require('../../assets/catalog/onboardingRatingSecondIcon.png'),
  onboardingRatingSixthIcon: require('../../assets/catalog/onboardingRatingSixthIcon.png'),
  onboardingRatingThirdIcon: require('../../assets/catalog/onboardingRatingThirdIcon.png'),
  welcomeScreenImg: require('../../assets/catalog/welcomeScreenImg.png'),
  giftArrow: require('../../assets/catalog/giftArrow.png'),
  giftImg: require('../../assets/catalog/giftImg.png'),
  pillPointerShapeIcon: require('../../assets/catalog/pillPointerShapeIcon.png'),
  point1: require('../../assets/catalog/point1.png'),
  point2: require('../../assets/catalog/point2.png'),
  point3: require('../../assets/catalog/point3.png'),
  point4: require('../../assets/catalog/point4.png'),
  pw1: require('../../assets/catalog/pw1.png'),
  pw10: require('../../assets/catalog/pw10.png'),
  pw11: require('../../assets/catalog/pw11.png'),
  pw12: require('../../assets/catalog/pw12.png'),
  pw2: require('../../assets/catalog/pw2.png'),
  pw3: require('../../assets/catalog/pw3.png'),
  pw4: require('../../assets/catalog/pw4.png'),
  pw5: require('../../assets/catalog/pw5.png'),
  pw6: require('../../assets/catalog/pw6.png'),
  pw7: require('../../assets/catalog/pw7.png'),
  pw8: require('../../assets/catalog/pw8.png'),
  pw9: require('../../assets/catalog/pw9.png'),
  rightArrorIcon2: require('../../assets/catalog/rightArrorIcon2.png'),
  shieldIcon: shieldIconSvg,
  bunnyPencilImg: require('../../assets/catalog/bunnyPencilImg.png'),
  streakFaceCry: require('../../assets/catalog/streakFaceCry.png'),
  streakFaceHappy: require('../../assets/catalog/streakFaceHappy.png'),
  streakFaceIdle: require('../../assets/catalog/streakFaceIdle.png'),
  streakFaceSleep: require('../../assets/catalog/streakFaceSleep.png'),
  bunnyCry: require('../../assets/catalog/bunnyCry.png'),
  filterIcon: require('../../assets/catalog/filterIcon.png'),
  LeaveIcon: require('../../assets/catalog/LeaveIcon.png'),
  aboutIcon: require('../../assets/catalog/aboutIcon.png'),
  backIcon: require('../../assets/catalog/backIcon.png'),
  chevronIcon: require('../../assets/catalog/chevronIcon.png'),
  contactUsIcon: require('../../assets/catalog/contactUsIcon.png'),
  deleteIcon: deleteIconSvg,
  logoutIcon: logoutIconSvg,
  membersIcon: require('../../assets/catalog/membersIcon.png'),
  notificationIcon: require('../../assets/catalog/notificationIcon.png'),
  privacyIcon: require('../../assets/catalog/privacyIcon.png'),
  rateUsIcon: require('../../assets/catalog/rateUsIcon.png'),
  restoreIcon: require('../../assets/catalog/restoreIcon.png'),
  shareAppIcon: require('../../assets/catalog/shareAppIcon.png'),
  termsIcon: require('../../assets/catalog/termsIcon.png'),
  tryProBadge: require('../../assets/catalog/tryProBadge.png'),
  userIdIcon: require('../../assets/catalog/userIdIcon.png'),
  overviewMascot: require('../../assets/catalog/overviewMascot.png'),
  statsChampionIcon: require('../../assets/catalog/statsChampionIcon.png'),
  statsCheck: require('../../assets/catalog/statsCheck.png'),
  statsCross: require('../../assets/catalog/statsCross.png'),
  statsDash: require('../../assets/catalog/statsDash.png'),
  statsEmptyImg: require('../../assets/catalog/statsEmptyImg.png'),
  statsFaceHappy: require('../../assets/catalog/statsFaceHappy.png'),
  statsFaceIdle: require('../../assets/catalog/statsFaceIdle.png'),
  statsFaceMissed: require('../../assets/catalog/statsFaceMissed.png'),
  statsFaceSkipped: require('../../assets/catalog/statsFaceSkipped.png'),
  statsFireIcon: require('../../assets/catalog/statsFireIcon.png'),
  statsRiseIcon: require('../../assets/catalog/statsRiseIcon.png'),
  statsStreakMascot: require('../../assets/catalog/statsStreakMascot.png'),
  colorImg1: require('../../assets/catalog/colorImg1.png'),
  colorImg10: require('../../assets/catalog/colorImg10.png'),
  colorImg11: require('../../assets/catalog/colorImg11.png'),
  colorImg12: require('../../assets/catalog/colorImg12.png'),
  colorImg2: require('../../assets/catalog/colorImg2.png'),
  colorImg3: require('../../assets/catalog/colorImg3.png'),
  colorImg4: require('../../assets/catalog/colorImg4.png'),
  colorImg5: require('../../assets/catalog/colorImg5.png'),
  colorImg6: require('../../assets/catalog/colorImg6.png'),
  colorImg7: require('../../assets/catalog/colorImg7.png'),
  colorImg8: require('../../assets/catalog/colorImg8.png'),
  colorImg9: require('../../assets/catalog/colorImg9.png'),
  zone19Icon: require('../../assets/catalog/zone19Icon.png'),
  zone20Icon: require('../../assets/catalog/zone20Icon.png'),
  zone21Icon: require('../../assets/catalog/zone21Icon.png'),
  zone22Icon: require('../../assets/catalog/zone22Icon.png'),
  zone23Icon: require('../../assets/catalog/zone23Icon.png'),
  zone24Icon: require('../../assets/catalog/zone24Icon.png'),
  zone25Icon: require('../../assets/catalog/zone25Icon.png'),
  zone26Icon: require('../../assets/catalog/zone26Icon.png'),
  zone27Icon: require('../../assets/catalog/zone27Icon.png'),
  zone28Icon: require('../../assets/catalog/zone28Icon.png'),
  zone29Icon: require('../../assets/catalog/zone29Icon.png'),
  zone30Icon: require('../../assets/catalog/zone30Icon.png'),
  zone31Icon: require('../../assets/catalog/zone31Icon.png'),
  zone32Icon: require('../../assets/catalog/zone32Icon.png'),
  zone33Icon: require('../../assets/catalog/zone33Icon.png'),
  zone34Icon: require('../../assets/catalog/zone34Icon.png'),
  zone35Icon: require('../../assets/catalog/zone35Icon.png'),
  zone36Icon: require('../../assets/catalog/zone36Icon.png'),
  zone37Icon: require('../../assets/catalog/zone37Icon.png'),
  zone38Icon: require('../../assets/catalog/zone38Icon.png'),
  zone39Icon: require('../../assets/catalog/zone39Icon.png'),
  zone40Icon: require('../../assets/catalog/zone40Icon.png'),
  zone41Icon: require('../../assets/catalog/zone41Icon.png'),
  zone42Icon: require('../../assets/catalog/zone42Icon.png'),
  zoneCalendarIcon: zoneCalendarIconSvg,
  zoneDownloadIcon: zoneDownloadIconSvg,
  editZoneIcon: editZoneIconSvg,
  markDoneIcon: markDoneIconSvg,
  moreVerticalIcon: moreVerticalIconSvg,
} as const;
