/**
 * withLaunchScreenFill — makes the Android launch screen paint the FULL screen
 * instead of showing the artwork as a small centred icon on a blank field.
 *
 * PORTED FROM ARBORA (`React-Native/Arbora/plugins/withLaunchScreenFill.js`),
 * which in turn ports TC9's hand-written native files. ChoreBuddy gitignores
 * `android/`, and `expo prebuild` also wipes the release signing block out of
 * `android/app/build.gradle`, so the edit has to exist BOTH as this plugin (so
 * a future prebuild reproduces it) and directly in `android/` (so no prebuild
 * has to run today). See the session log for 2026-08-31.
 *
 * WHAT THE USER SEES, AND WHICH PART THIS FIXES
 * ---------------------------------------------
 * There are TWO screens on Android 12+, and the legacy `expo.splash` block only
 * ever governed the pre-12 one:
 *
 *   1. The SYSTEM splash (`Theme.App.SplashScreen`) — the platform draws
 *      `windowSplashScreenAnimatedIcon` centred in a fixed icon slot on
 *      `windowSplashScreenBackground`. Android sizes that slot itself and
 *      scales the image to FIT, which is why ChoreBuddy's whole 1125x2436
 *      launch artwork appeared as a small centred rectangle. **This is not
 *      overridable by design** — no drawable makes the system splash
 *      full-bleed, and its background accepts a COLOR only, never a gradient.
 *   2. The window that takes over via `postSplashScreenTheme` (`AppTheme`),
 *      which holds until React Native's view attaches — and holds again for as
 *      long as `App.tsx` returns `null` while `useFonts` resolves. Expo leaves
 *      `AppTheme` with NO `android:windowBackground`, so that window was blank.
 *
 * This plugin fills (2) with the launch artwork over the pink gradient,
 * matching iOS `LaunchScreen.storyboard`'s full-bleed layout, and (1) is
 * handled in `app.json`: `expo-splash-screen` gets a BLANK 48x48 transparent
 * PNG at `imageWidth: 1` on the flat `#FED6DC`, so the system splash renders as
 * a bare pink field with no icon rather than shrinking the launch canvas into
 * the icon slot. The sequence is therefore flat pink -> full-bleed artwork,
 * with nothing jumping in size and no pale-lavender frame at either end.
 *
 * `android:gravity="fill"` is TC9/Arbora's choice and is kept for parity. It
 * STRETCHES on both axes rather than aspect-filling like iOS's
 * `scaleAspectFill`: harmless on a phone (splash.png is 1125x2436 = 0.462, a
 * 1080x2400 device is 0.450, under 3% distortion) but it WOULD distort on a
 * tablet. If that ever matters, pre-render per-orientation assets rather than
 * changing the gravity — there is no centre-crop for a layer-list `<bitmap>`.
 */

const { withDangerousMod, withAndroidStyles, withMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** Matches TC9/Arbora's resource names so the trees stay greppable together. */
const BITMAP_NAME = 'launch_screen_bg.png';
const DRAWABLE_NAME = 'launch_screen.xml';
const GRADIENT_NAME = 'launch_screen_gradient.xml';

/** The SwiftUI gradient the user specified, as sRGB hex. */
const GRADIENT_TOP = '#FFD6DC'; // Color(red: 1, green: 0.84, blue: 0.86)
const GRADIENT_BOTTOM = '#FCA3B0'; // Color(red: 0.99, green: 0.64, blue: 0.69)

const GENERATED = (body) => `<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by plugins/withLaunchScreenFill.js — do not edit by hand, this file
  is recreated on every prebuild.
-->
${body}`;

/**
 * Base layer. The system splash can only take a flat colour, so the gradient
 * lives here, on the window that follows it. The artwork on top is opaque, so
 * this only shows through if a future asset ever has transparency — but it
 * guarantees that whatever does show is pink rather than the theme's default
 * white.
 */
const GRADIENT_DRAWABLE = GENERATED(`<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:type="linear"
        android:angle="270"
        android:startColor="${GRADIENT_TOP}"
        android:endColor="${GRADIENT_BOTTOM}" />
</shape>
`);

/**
 * Full-bleed launch background, ported from iOS `launchScreenBG`. Used as
 * `android:windowBackground` on `AppTheme` so the launch artwork paints the
 * whole screen — status and navigation bar zones included — between the Android
 * 12+ SplashScreen handoff and React Native's view attaching.
 */
const LAYER_LIST = GENERATED(`<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/launch_screen_gradient" />
    <item>
        <bitmap
            android:src="@drawable/launch_screen_bg"
            android:gravity="fill" />
    </item>
</layer-list>
`);

/**
 * Copy the splash artwork in and write the drawables beside it.
 *
 * The artwork path comes from THIS plugin's own options, not `expo.splash` —
 * that block no longer exists. `expo-splash-screen` is now configured with a
 * deliberately blank 1dp image so the system splash is a bare colour (see the
 * header), so there is no full-size artwork left in the Expo config to read.
 */
function withLaunchScreenDrawables(config, opts) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const res = path.join(cfg.modRequest.platformProjectRoot, 'app/src/main/res');

      const light = opts?.image ?? cfg.splash?.image;
      // ChoreBuddy is light-only (`userInterfaceStyle: "light"`), but AppTheme's
      // parent is DayNight, so a night-qualified copy still has to exist or a
      // device in dark mode falls back to the theme default.
      const dark = opts?.darkImage ?? cfg.splash?.dark?.image ?? light;

      if (!light) {
        throw new Error(
          '[withLaunchScreenFill] no artwork configured — pass { image } in the ' +
            'plugin options (app.json).'
        );
      }

      for (const [dir, source] of [
        ['drawable-nodpi', light],
        ['drawable-night-nodpi', dark],
      ]) {
        const from = path.join(cfg.modRequest.projectRoot, source);
        if (!fs.existsSync(from)) {
          throw new Error(`[withLaunchScreenFill] missing asset: ${from}`);
        }
        const target = path.join(res, dir);
        fs.mkdirSync(target, { recursive: true });
        fs.copyFileSync(from, path.join(target, BITMAP_NAME));
      }

      const drawableDir = path.join(res, 'drawable');
      fs.mkdirSync(drawableDir, { recursive: true });
      fs.writeFileSync(path.join(drawableDir, GRADIENT_NAME), GRADIENT_DRAWABLE);
      fs.writeFileSync(path.join(drawableDir, DRAWABLE_NAME), LAYER_LIST);

      return cfg;
    },
  ]);
}

/**
 * Point `AppTheme`'s windowBackground at the layer-list so the artwork reaches
 * every edge (iOS `.ignoresSafeArea()`). Transparent system bars come from
 * React Native's runtime `enableEdgeToEdge()`, not from theme attributes — see
 * the note in the body.
 *
 * The style is located BY NAME, not through
 * `AndroidConfig.Styles.assignStylesValue` + `getAppThemeLightNoActionBarGroup()`.
 * That helper matches on the parent as well, and Expo generates `AppTheme` with
 * parent `Theme.AppCompat.DayNight.NoActionBar` while the helper hardcodes
 * `...Light.NoActionBar` — so it appends a SECOND `<style name="AppTheme">` and
 * the build dies in `mergeReleaseResources` with "Found item Style/AppTheme
 * more than one time".
 */
function withLaunchScreenWindowBackground(config) {
  return withAndroidStyles(config, (cfg) => {
    const styles = cfg.modResults.resources?.style ?? [];
    const appTheme = styles.find((st) => st?.$?.name === 'AppTheme');
    if (!appTheme) {
      throw new Error(
        '[withLaunchScreenFill] no <style name="AppTheme"> in styles.xml — ' +
          'the template changed; re-check where postSplashScreenTheme points.'
      );
    }
    appTheme.item = appTheme.item ?? [];

    const put = (name, value) => {
      const existing = appTheme.item.find((it) => it?.$?.name === name);
      if (existing) existing._ = value;
      else appTheme.item.push({ $: { name }, _: value });
    };

    put('android:windowBackground', '@drawable/launch_screen');
    // The splash is light pink, so the system icons must be dark to stay legible.
    put('android:windowLightStatusBar', 'true');

    // `android:statusBarColor` / `android:navigationBarColor` are DELIBERATELY
    // not set here (2026-09-16). They are deprecated in API 35 and are no-ops
    // on this app's target 36, and Play Console flags them as "deprecated APIs
    // or parameters for edge-to-edge". They were also redundant: the window is
    // only created after `MainActivity.onCreate`, by which point Expo's
    // `EdgeToEdgePackage` has already called React Native's
    // `Window.enableEdgeToEdge()` (`WindowUtil.kt`), which sets both colours to
    // transparent programmatically on every API level. So there is no frame in
    // which the theme values could have applied. `app.json` must also keep its
    // `androidStatusBar` block absent, or `@expo/config-plugins`'
    // `withStatusBar` re-adds `android:statusBarColor` on the next prebuild.

    return cfg;
  });
}


/**
 * Strip the two deprecated edge-to-edge colour attributes from `AppTheme`
 * AFTER every other mod has run (2026-09-16).
 *
 * `android:statusBarColor` and `android:navigationBarColor` are deprecated in
 * API 35 and are no-ops on this app's target 36; Play Console reports them as
 * "deprecated APIs or parameters for edge-to-edge". They were also redundant —
 * the window is created after `MainActivity.onCreate`, by which point Expo's
 * `EdgeToEdgePackage` has called React Native's `Window.enableEdgeToEdge()`
 * (`WindowUtil.kt`), which sets both to transparent programmatically on every
 * API level — so there is no frame in which the theme values could apply.
 *
 * This CANNOT be done by simply not writing them in the styles mod above:
 *  - `@expo/config-plugins`' `AndroidConfig.StatusBar.withStatusBar` is
 *    registered by `withAndroidExpoPlugins`, i.e. AFTER every plugin listed in
 *    `app.json`, so its `withAndroidStyles` mod runs last and re-adds
 *    `android:statusBarColor`.
 *  - Removing the `androidStatusBar` block from `app.json` does not stop it.
 *    `expo-splash-screen`'s prebuild plugin back-fills
 *    `androidStatusBar.backgroundColor` from the splash colour
 *    (`withAndroidSplashScreen.js:61-67`), so `withStatusBar` would write an
 *    OPAQUE `#FED6DC` status bar — worse than the transparent value it had.
 *
 * So the removal runs in the `finalized` mod, which the mod compiler sorts to
 * the very end of the Android pass (`mod-compiler.js` `precedences`).
 */
function withoutDeprecatedSystemBarColors(config) {
  return withMod(config, {
    platform: 'android',
    mod: 'finalized',
    action: async (cfg) => {
      const styles = path.join(
        cfg.modRequest.platformProjectRoot,
        'app/src/main/res/values/styles.xml'
      );
      if (!fs.existsSync(styles)) return cfg;

      const before = fs.readFileSync(styles, 'utf8');
      const after = before.replace(
        /^[ \t]*<item name="android:(?:statusBarColor|navigationBarColor)">.*<\/item>[ \t]*\r?\n/gm,
        ''
      );
      if (after !== before) fs.writeFileSync(styles, after);

      return cfg;
    },
  });
}

module.exports = function withLaunchScreenFill(config, opts) {
  return withoutDeprecatedSystemBarColors(
    withLaunchScreenWindowBackground(withLaunchScreenDrawables(config, opts))
  );
};
