/**
 * withQuickActionIcons — Android vector drawables for the launcher long-press
 * quick actions (`src/services/QuickActions.ts`).
 *
 * PORTED FROM ARBORA (`React-Native/Arbora/plugins/withQuickActionIcons.js`),
 * same reasoning as `withLaunchScreenFill`: `android/` is gitignored and
 * `expo prebuild` regenerates it (and wipes the release signing block out of
 * `android/app/build.gradle`), so the resources must exist BOTH as this plugin —
 * so a future prebuild reproduces them — and directly under `android/` today.
 *
 * WHY RESOURCES AT ALL: `expo-quick-actions` resolves an Android shortcut icon
 * by resource NAME (`ExpoQuickActionsModule.kt` →
 * `getIdentifier(icon, "drawable", packageName)` → `Icon.createWithResource`), so
 * it cannot take the `react-native-svg` components the app's 42 vector assets are
 * used as. Without a drawable the launcher draws an empty placeholder square.
 *
 * WHY THESE TWO GLYPHS: iOS asks the SYSTEM for its icons —
 * `UIApplicationShortcutIcon(type: .love)` and `(type: .mail)`
 * (`QuickActionManager.swift`). There is no ChoreBuddy asset behind them, and the
 * catalog has neither a heart nor an envelope, so the Android equivalents are the
 * platform's own standard heart and envelope outlines. Nothing is invented: these
 * are the same two universal glyphs iOS pulls from UIKit, expressed as
 * VectorDrawables and tinted with the app's own `appPurple`.
 *
 * DAY/NIGHT: a shortcut icon is rendered by the LAUNCHER, in the launcher's own
 * context, so it follows the SYSTEM theme and not the app (which is
 * `userInterfaceStyle: light`). A single dark-on-transparent glyph would vanish in
 * a dark popup, so both variants ship. The literals are fixed on purpose — a
 * launcher cannot read anything from the app's own theme.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** `colors.purple` (#9871E8), and a lifted variant for the dark popup. */
const INK_LIGHT = '#9871E8';
const INK_DARK = '#C4ABF5';

/**
 * Standard 24x24 heart and envelope outlines — the same shapes UIKit's `.love`
 * and `.mail` shortcut icons draw.
 */
const PATHS = {
  ic_shortcut_gift:
    'M12 20.3l-1.1-1C6.1 15 3 12.2 3 8.8A4.3 4.3 0 0 1 7.4 4.5c1.4 0 2.7.6 3.6 1.7l1 1.2 1-1.2a4.7 4.7 0 0 1 3.6-1.7A4.3 4.3 0 0 1 21 8.8c0 3.4-3.1 6.2-7.9 10.5l-1.1 1z',
  ic_shortcut_help:
    'M4 6.5h16c.6 0 1 .4 1 1v9c0 .6-.4 1-1 1H4c-.6 0-1-.4-1-1v-9c0-.6.4-1 1-1zm.6 1.4L12 13l7.4-5.1',
};

function vector(pathData, stroke) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withQuickActionIcons.js — do not edit; prebuild overwrites it. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:pathData="${pathData}"
      android:strokeColor="${stroke}"
      android:strokeWidth="1.75"
      android:strokeLineCap="round"
      android:strokeLineJoin="round" />
</vector>
`;
}

/** Exported so the resources can also be written straight into `android/`. */
const VARIANTS = [
  ['drawable', INK_LIGHT],
  ['drawable-night', INK_DARK],
];

function writeIcons(resDir) {
  for (const [dir, stroke] of VARIANTS) {
    const outDir = path.join(resDir, dir);
    fs.mkdirSync(outDir, { recursive: true });
    for (const [name, d] of Object.entries(PATHS)) {
      fs.writeFileSync(path.join(outDir, `${name}.xml`), vector(d, stroke), 'utf8');
    }
  }
}

module.exports = function withQuickActionIcons(config) {
  return withDangerousMod(config, [
    'android',
    async cfg => {
      writeIcons(path.join(cfg.modRequest.platformProjectRoot, 'app/src/main/res'));
      return cfg;
    },
  ]);
};

module.exports.writeIcons = writeIcons;
